{% extends 'base.swig' %}

{% block head %}
    James Mario Davis
{% endblock head %}

{% block top_nav %}
    <ul>
        <li><a href="/"> Home </a> </li>
        <li><a href="/papers"> Papers </a> </li>
        <li><a href="/presentations"> Presentations </a> </li>
        <li><a href="/cv/cvAcademic.pdf"> CV </a> </li>
        <li><a href="/contact"> Contact </a> </li>
    </ul>
{% endblock top_nav %}